substitutions:
  device_name: "iotcasa-2gang-switch"
  friendly_namez: "z"
  project_name: "IOTCASA.2 Gang Switch"
  project_version: "1.2"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_namez}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp07s
  restore_from_flash: true
  early_pin_init: false

preferences:
  flash_write_interval: 1min

api:

logger:
  baud_rate: 0

ota:
  - platform: esphome

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://mahipat99/ESPYz12/2ch.yaml

status_led:
  pin:
    number: GPIO2

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "${friendly_namez} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset

  - platform: safe_mode
    name: "Safe Mode"
    internal: false

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO12
    icon: mdi:light-switch

  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:lightbulb
    

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Button"
    disabled_by_default: true
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: true
    icon: 'mdi:button-pointer'
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.toggle: relay_1

  - platform: gpio
    name: "Switch 1"
    pin: GPIO16
    on_press:
      - switch.turn_on: relay_1
    on_release:
      - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 50ms

  - platform: gpio
    name: "Switch 2"
    pin: GPIO14
    on_press:
      - switch.turn_on: relay_2
    on_release:
      - switch.turn_off: relay_2
    filters:
      - delayed_on_off: 50ms