substitutions:
  device_name: 2ch
  friendly_name: 2ch
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: False
  project:
    name: "Generic.2CH"
    version: "1.2"

esp8266:
  board: esp07s
  early_pin_init: false

logger:

api:

web_server:
  port: 80

ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://mahipat99/ESPY/2ch.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "2Ch Fallback Hotspot"
    password: "blablabla"
    ap_timeout: 2min
  reboot_timeout: 5min

captive_portal:

status_led:
  pin:
    number: GPIO2

button:
  - platform: restart
    name: "Restart"
    id: button_restart
  - platform: factory_reset
    name: Restart with Factory Default Settings

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO12
    icon: mdi:light-switch
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:lightbulb

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    name: "Button"
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: true
    icon: 'mdi:button-pointer'
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    name: "Switch 1"
    pin: GPIO16
    on_press:
      then:
        - switch.turn_on: relay_1
    on_release:
      then:
        - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "Switch 2"
    pin: GPIO14
    on_press:
      then:
        - switch.turn_on: relay_2
    on_release:
      then:
        - switch.turn_off: relay_2
    filters:
      - delayed_on_off: 50ms
