substitutions:
  device_name: "athom-1gang-switch"
  friendly_namez: "z"
  project_name: "Athom Technology.1 Gang Switch"
  project_version: "1.1.1"
  light_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_namez}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-sw01.yaml

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Button"
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: true
    icon: 'mdi:button-pointer'
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.toggle: relay_1

  - platform: gpio
    name: "Switch 1"
    pin: GPIO16
    on_press:
      - switch.turn_on: relay_1
    on_release:
      - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 50ms

  - platform: gpio
    name: "Switch 2"
    pin: GPIO14
    on_press:
      - switch.turn_on: relay_2
    on_release:
      - switch.turn_off: relay_2
    filters:
      - delayed_on_off: 50ms

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "${friendly_namez} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset

  - platform: safe_mode
    name: "Safe Mode"
    internal: false

output:
  # Relay
  - platform: gpio
    pin: GPIO13
    id: relay1
