substitutions:
  device_name: "2ch"
  friendly_name: ""
  project_name: "IOTCASA.2 Gang Switch"
  project_version: "1.2"
  light_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp07s
  restore_from_flash: true
  early_pin_init: false

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "2Ch Fallback Hotspot"
    password: "blablabla"
    ap_timeout: 2min
  reboot_timeout: 5min

captive_portal:

dashboard_import:
  package_import_url: github://mahipat99/ESPY/2ch.yaml

status_led:
  pin:
    number: GPIO2

button:
  - platform: restart
    name: "Restart"
    id: button_restart

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO12
    icon: mdi:light-switch
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:lightbulb

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    name: "Button"
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: true
    icon: 'mdi:button-pointer'
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    name: "Switch 1"
    pin: GPIO16
    on_press:
      then:
        - switch.turn_on: relay_1
    on_release:
      then:
        - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: " Switch 2"
    pin: GPIO14
    on_press:
      then:
        - switch.turn_on: relay_2
    on_release:
      then:
        - switch.turn_off: relay_2
    filters:
      - delayed_on_off: 50ms
