substitutions:
  device_name: "iotcasa-2gang-switch"
  friendly_name: ""
  room: ""
  project_name: "IOTCasa.2 Gang Switch"
  project_version: "1.2"
  device_description: "IOTCasa 2 Gang Switch"
  relay_restore_mode: RESTORE_DEFAULT_OFF
  wifi_fast_connect: "False"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: "${room}"
  comment: ${device_description}
  name_add_mac_suffix: True
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp07s
  early_pin_init: False
  restore_from_flash: True

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  level : ERROR

mdns:
  disabled: False

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.
  fast_connect: "${wifi_fast_connect}"

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   fast_connect: "${wifi_fast_connect}"
#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "${device_name}"
#     password: "blablabla"
#     ap_timeout: 2min
#   reboot_timeout: 5min

captive_portal:

dashboard_import:
  package_import_url: github://mahipat99/ESPY/2ch.yaml

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: True
    pin: GPIO2

button:
  - platform: restart
    name: "Restart"
    id: button_restart

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    disabled_by_default: True

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO12
    icon: mdi:light-switch
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:lightbulb

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Button"
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: True
    icon: 'mdi:button-pointer'
    filters:
      - delayed_on_off: 50ms
    disabled_by_default: True
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay_1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: gpio
    name: "Switch 1"
    pin: GPIO16
    on_press:
      - switch.turn_on: relay_1
    on_release:
      - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "Switch 2"
    pin: GPIO14
    on_press:
      - switch.turn_on: relay_2
    on_release:
      - switch.turn_off: relay_2
    filters:
      - delayed_on_off: 50ms