substitutions:
  device_name: "4gang-switch"
  friendly_name: ""
  room: ""
  project_name: "Generic.4 Gang Switch"
  project_version: "1.4"
  device_description: "4 Gang switch configured for push button use"
  relay_restore_mode: RESTORE_DEFAULT_OFF
  wifi_fast_connect: "False"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: "${room}"
  comment: ${device_description}
  name_add_mac_suffix: True
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp12e
  restore_from_flash: True

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0
  level: ERROR

mdns:
  disabled: False

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.
  fast_connect: "${wifi_fast_connect}"

captive_portal:

dashboard_import:
  package_import_url: github://harigopal/iotcasa-configs/4ch-push-button.yaml

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: True
    pin:
      number: GPIO2
      inverted: True

button:
  - platform: restart
    name: "Restart"
    id: button_restart

  - platform: factory_reset
    name: "Factory Reset"
    id: Reset
    disabled_by_default: True

event:
  - platform: template
    name: "Switch 1 Single Press"
    id: switch_1_single
    event_types:
      - "single_press"

  - platform: template
    name: "Switch 1 Double Press"
    id: switch_1_double
    event_types:
      - "double_press"

  - platform: template
    name: "Switch 1 Hold"
    id: switch_1_hold
    event_types:
      - "hold"

  - platform: template
    name: "Switch 2 Single Press"
    id: switch_2_single
    event_types:
      - "single_press"

  - platform: template
    name: "Switch 2 Double Press"
    id: switch_2_double
    event_types:
      - "double_press"

  - platform: template
    name: "Switch 2 Hold"
    id: switch_2_hold
    event_types:
      - "hold"

  - platform: template
    name: "Switch 3 Single Press"
    id: switch_3_single
    event_types:
      - "single_press"

  - platform: template
    name: "Switch 3 Double Press"
    id: switch_3_double
    event_types:
      - "double_press"

  - platform: template
    name: "Switch 3 Hold"
    id: switch_3_hold
    event_types:
      - "hold"

  - platform: template
    name: "Switch 4 Single Press"
    id: switch_4_single
    event_types:
      - "single_press"

  - platform: template
    name: "Switch 4 Double Press"
    id: switch_4_double
    event_types:
      - "double_press"

  - platform: template
    name: "Switch 4 Hold"
    id: switch_4_hold
    event_types:
      - "hold"

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO15
    icon: mdi:electric-switch
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO04
    icon: mdi:electric-switch
  - platform: gpio
    name: "Relay 3"
    id: relay_3
    restore_mode: "${relay_restore_mode}"
    pin: GPIO14
    icon: mdi:electric-switch
  - platform: gpio
    name: "Relay 4"
    id: relay_4
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:electric-switch

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Button"
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: True
    filters:
      - delayed_on_off: 50ms
    disabled_by_default: True
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay_1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  # Enhanced Switch 1 with multiple press types
  - platform: gpio
    name: "Switch 1"
    id: switch_1
    pin: GPIO03
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
      # Single press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_1_single
              event_type: single_press
      # Double press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_1_double
              event_type: double_press
      # Long press (hold) - toggle relay directly and fire event
      - timing:
          - ON for at least 2s
        then:
          - switch.toggle: relay_1
          - event.trigger:
              id: switch_1_hold
              event_type: hold

  # Enhanced Switch 2 with multiple press types
  - platform: gpio
    name: "Switch 2"
    id: switch_2
    pin: GPIO05
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
      # Single press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_2_single
              event_type: single_press
      # Double press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_2_double
              event_type: double_press
      # Long press (hold) - toggle relay directly and fire event
      - timing:
          - ON for at least 2s
        then:
          - switch.toggle: relay_2
          - event.trigger:
              id: switch_2_hold
              event_type: hold

  # Enhanced Switch 3 with multiple press types
  - platform: gpio
    name: "Switch 3"
    id: switch_3
    pin: GPIO016
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
      # Single press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_3_single
              event_type: single_press
      # Double press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_3_double
              event_type: double_press
      # Long press (hold) - toggle relay directly and fire event
      - timing:
          - ON for at least 2s
        then:
          - switch.toggle: relay_3
          - event.trigger:
              id: switch_3_hold
              event_type: hold

  # Enhanced Switch 4 with multiple press types
  - platform: gpio
    name: "Switch 4"
    id: switch_4
    pin: GPIO012
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
      # Single press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_4_single
              event_type: single_press
      # Double press - fire ESPHome event
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.3s
        then:
          - event.trigger:
              id: switch_4_double
              event_type: double_press
      # Long press (hold) - toggle relay directly and fire event
      - timing:
          - ON for at least 2s
        then:
          - switch.toggle: relay_4
          - event.trigger:
              id: switch_4_hold
              event_type: hold
