substitutions:
  device_name: "iotcasa-1gang-switch"
  friendly_name: "test"
  project_name: "IOTCASA.1 Gang Switch"
  project_version: "1.2"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true
  early_pin_init: false

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://mahipat99/ESPY-config/athom.yaml

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: uptime
    name: "Uptime Sensor"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset

  - platform: restart
    name: "Restart"
    id: button_restart

  - platform: safe_mode
    name: "Safe Mode"
    internal: false

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO12
    icon: mdi:light-switch
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:lightbulb
