substitutions:
  device_name: "athom-1gang-switch"
  friendly_name: ""
  project_name: "Athom Technology.1 Gang Switch"
  project_version: "1.1.1"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://mahipat99/ESPY-config/atom.yaml

button:
  - platform: restart
    name: "Restart"
    id: button_restart
  - platform: factory_reset
    name: Restart with Factory Default Settings

sensor:
  - platform: uptime
    name: "Uptime Sensor"
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay_1
    restore_mode: "${relay_restore_mode}"
    pin: GPIO12
    icon: mdi:light-switch
  - platform: gpio
    name: "Relay 2"
    id: relay_2
    restore_mode: "${relay_restore_mode}"
    pin: GPIO13
    icon: mdi:lightbulb

binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    name: "Button"
    disabled_by_default: true
    pin:
      number: GPIO0
      mode: input_pullup
      inverted: true
    icon: 'mdi:button-pointer'
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    name: "Switch 1"
    pin: GPIO16
    on_press:
      then:
        - switch.turn_on: relay_1
    on_release:
      then:
        - switch.turn_off: relay_1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: " Switch 2"
    pin: GPIO14
    on_press:
      then:
        - switch.turn_on: relay_2
    on_release:
      then:
        - switch.turn_off: relay_2
    filters:
      - delayed_on_off: 50ms
